# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-14 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KaoLa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_src', models.CharField(max_length=100)),
                ('middle_src', models.CharField(max_length=100)),
                ('big_src', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=100)),
                ('discount_price', models.CharField(max_length=40)),
                ('orig_price', models.CharField(max_length=40)),
            ],
        ),
    ]
