# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-14 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KaoLa', '0002_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='des',
            field=models.CharField(max_length=200),
        ),
    ]
