# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KaoLa', '0003_auto_20190314_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('passwrod', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
