# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KaoLa', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isselect', models.BooleanField(default=True)),
                ('number', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KaoLa.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KaoLa.User')),
            ],
        ),
    ]
